"""ENG — engine registry + the claude / codex adapters, exercised through `tx spawn`, `tx fork`,
`tx resume`, `tx handover`, `tx archive`, `tx hook` (spec section 03, cases T-ENG-*). Antigravity
cases are deferred (D3) and have no test here.

Fixture F-ENG: a fresh home whose `agents/` is a PLAIN dir (`COMMON.md` body `C` with no
frontmatter, `roleP.md` body `P`, skill `foo`), both hook shim sets, the H4 repo as `--cwd`, fakes
on PATH. A crafted source record S is an exited llm record with `cmd` = the source command under
test and one captured chat.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import shlex
import shutil
import subprocess
import time
import uuid
from pathlib import Path

from txkit import TX_BIN, TxCase, expected_failure_on_python

CLAUDE_YOLO = "--dangerously-skip-permissions"
CLAUDE_RO_BLOCK = [
    "--allowedTools",
    "Bash",
    "--disallowedTools",
    "Edit",
    "Write",
    "NotebookEdit",
    "--permission-mode",
    "dontAsk",
    "--setting-sources",
    "user",
]
CODEX_DEFAULTS = ["codex", "-m", "gpt-5.6-sol", "-c", "model_reasoning_effort=high"]
CODEX_YOLO = ["--dangerously-bypass-approvals-and-sandbox", "--dangerously-bypass-hook-trust"]
CODEX_RO_BLOCK = [
    "--sandbox",
    "danger-full-access",
    "--ask-for-approval",
    "never",
    "--dangerously-bypass-hook-trust",
]
UPDATE_CHECK_TOKENS = ["-c", "check_for_update_on_startup=false"]

CURL_STUB = r'''#!/bin/bash
# stub curl — GENERATED by test_eng.py: dump argv + env, honour -o, optionally wait/fail.
python3.14 - "$@" <<'PY'
import json, os, sys, time
argv = sys.argv[1:]
out_dir = os.environ["CURL_STUB_OUT"]
os.makedirs(out_dir, exist_ok=True)
with open(os.path.join(out_dir, f"curl-{os.getpid()}.json"), "w") as handle:
    json.dump({"argv": argv, "env": dict(os.environ)}, handle)
gate = os.environ.get("CURL_STUB_GATE")
if gate:
    deadline = time.time() + 20
    while not os.path.exists(gate) and time.time() < deadline:
        time.sleep(0.05)
if os.environ.get("CURL_STUB_FAIL"):
    sys.exit(3)
if "-o" in argv:
    with open(argv[argv.index("-o") + 1], "w") as handle:
        handle.write("echo ok\n")
PY
exit $?
'''


def argv_of(dump: dict) -> list[str]:
    """The fake's argv with the binary reduced to its basename (the fake lives at a temp path)."""
    return [os.path.basename(dump["argv"][0]), *dump["argv"][1:]]


class TestEng(TxCase):
    home_options = {"link_agents": False}

    def setUp(self) -> None:
        super().setUp()
        agents = self.home.agents
        (agents / "skills" / "foo").mkdir(parents=True)
        (agents / "COMMON.md").write_text("C\n")
        (agents / "roleP.md").write_text("P\n")
        (agents / "skills" / "foo" / "SKILL.md").write_text(
            "---\nname: foo\ndescription: d\n---\nbody\n"
        )
        self.repo = str(self.git.path)

    # ----- helpers -----------------------------------------------------------------------------

    def show(self, name_or_id: str) -> dict:
        result = self.tx(["show", name_or_id])
        self.assertEqual(result.code, 0, result.err)
        return json.loads(result.out)

    def spawn(
        self, name: str, *arguments: str, env: dict | None = None, cwd: str | None = None, fake: str | None = None
    ) -> tuple[dict, dict]:
        """`tx spawn name --tag t --cwd <repo> *arguments` → (record, dump of the fake that ran —
        the record's engine unless `fake` names the binary the command actually invokes)."""
        result = self.tx(
            ["spawn", name, "--tag", "t", "--cwd", cwd or self.repo, *arguments], env=env
        )
        self.assertEqual(result.code, 0, result.err)
        record = self.show(name)
        return record, self.fakes.wait_dump(fake or record["engine"], record["id"])

    def source(
        self,
        name: str,
        cmd: str,
        *,
        engine: str = "claude",
        chat: str | None = None,
        env: dict | None = None,
        cwd: str | None = None,
        chat_cwd: str | None = None,
        transcript: str | None = None,
        state: str = "exited",
    ) -> tuple[str, str]:
        """A crafted source record S with one captured chat; returns (record id, chat id)."""
        session_id = str(uuid.uuid4())
        chat_id = chat or f"c-{uuid.uuid4().hex[:8]}"
        record_cwd = cwd or self.repo
        self.records.llm(
            id=session_id,
            name=name,
            state=state,
            cwd=record_cwd,
            cmd=cmd,
            env=env or {},
            engine=engine,
            created_at=time.time() - 100,
            ended_at=time.time() - 50 if state in ("exited", "archived") else None,
            chats=[
                self.records.chat_ref(
                    session_id=session_id,
                    id=chat_id,
                    cwd=chat_cwd or record_cwd,
                    started_at=time.time() - 100,
                    engine=engine,
                )
            ],
        )
        if transcript is not None:
            self.write_claude_transcript(chat_cwd or record_cwd, chat_id, transcript)
        return session_id, chat_id

    def write_claude_transcript(self, cwd: str, chat_id: str, text: str) -> Path:
        path = self.home.claude_transcript_path(cwd, chat_id)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
        return path

    def write_rollout(self, chat_id: str, date_dir: str = "2026/09/16", text: str = '{"type":"session_meta"}\n') -> Path:
        path = self.home.codex_home / "sessions" / date_dir / f"rollout-2026-09-16T10-00-00-{chat_id}.jsonl"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
        return path

    def fork(self, source_name: str, new_name: str, *arguments: str) -> tuple[dict, dict]:
        result = self.tx(["fork", source_name, new_name, *arguments])
        self.assertEqual(result.code, 0, result.err)
        record = self.show(new_name)
        return record, self.fakes.wait_dump(record["engine"], record["id"])

    def resume(self, source_name: str, *arguments: str, env: dict | None = None):
        result = self.tx(["resume", source_name, *arguments], env=env)
        self.assertEqual(result.code, 0, result.err)
        new_id = re.search(r"cwd=(.*)\)$", result.out).group(0)  # noqa: F841 — presence check only
        return result

    def latest_record_named(self, name: str) -> dict:
        """The most recently created record with this display name (`tx show` prefers the live one,
        which is the same thing right after a spawn)."""
        return self.show(name)

    def worktree_for(self, name: str) -> Path:
        """`$TX_IDE_HOME/worktrees/<repo>-<hash>/<repo>--<name>` for the git fixture."""
        common = Path(self.git.git("rev-parse", "--git-common-dir").strip())
        if not common.is_absolute():
            common = self.git.path / common
        digest = hashlib.sha256(str(common.resolve()).encode()).hexdigest()[:8]
        return self.home.worktrees_dir / f"{self.git.path.name}-{digest}" / f"{self.git.path.name}--{name}"

    def reap_watchers(self) -> None:
        """Kill the detached `_chat-op-watch` children a distiller-path handover leaves behind."""
        if not self.home.chat_ops_dir.is_dir():
            return
        for op_dir in self.home.chat_ops_dir.iterdir():
            subprocess.run(["pkill", "-f", f"_chat-op-watch {op_dir.name}"])

    def handover_seed(self, source_id: str, chat_id: str, task: str, slug: str, op_id: str) -> str:
        home = self.home.path
        return (
            f"You are a tx-ide handover distiller (a temporary helper). Read the predecessor chat "
            f"bundle at {home}/history/{source_id}/{chat_id}/transcript.jsonl . "
            f"Distill a focused, self-contained brief for this task and write it to "
            f"{home}/history/{source_id}/handover-{slug}.md : "
            f"«{task}». Capture only what the new worker needs to start — relevant context, current "
            f"state, constraints, and key file paths — not the whole history. When the brief file is "
            f"saved, run exactly this command and nothing else: "
            f"env TX_IDE_HOME={shlex.quote(str(home))} {shlex.quote(TX_BIN)} _chat-op-finish {shlex.quote(op_id)}"
        )

    def self_catch_up_seed(self, source_id: str, chat_id: str) -> str:
        return (
            f"You are taking over work via tx handover. There is no pre-written brief — read the "
            f"predecessor bundle at {self.home.history_dir}/{source_id}/{chat_id}/ (transcript.jsonl + "
            f"subagents/ + tool-results/), write yourself a short brief of the task and its state, then begin."
        )

    def only_op_id(self) -> str:
        ops = sorted(path.name for path in self.home.chat_ops_dir.iterdir())
        self.assertEqual(len(ops), 1, ops)
        return ops[0]

    def exclude_lines(self) -> list[str]:
        exclude = self.git.path / ".git" / "info" / "exclude"
        return exclude.read_text().splitlines() if exclude.is_file() else []

    # ----- registry + shared constants --------------------------------------------------------

    def test_t_eng_01_effort_levels_and_default(self):
        _, dump = self.spawn("c0", "--engine", "claude")
        self.assertEqual(dump["argv"][dump["argv"].index("--effort") + 1], "high")
        tiers = {1: "low", 2: "medium", 3: "high", 4: "xhigh", 5: "max"}
        for effort, tier in tiers.items():
            _, dump = self.spawn(f"c{effort}", "--engine", "claude", "--effort", str(effort))
            self.assertEqual(dump["argv"][dump["argv"].index("--effort") + 1], tier)
            _, dump = self.spawn(f"x{effort}", "--engine", "codex", "--effort", str(effort))
            self.assertIn(f"model_reasoning_effort={tier}", dump["argv"])
            self.assertEqual(dump["argv"][dump["argv"].index("-c") + 1], f"model_reasoning_effort={tier}")
        for bad in ("0", "6"):
            result = self.tx(["spawn", "bad", "--tag", "t", "--engine", "claude", "--effort", bad, "--cwd", self.repo])
            self.assertEqual(result.code, 2)
            self.assertTrue(
                result.err.rstrip().endswith(
                    f"tx spawn: error: argument --effort: invalid choice: '{bad}' (choose from '1', '2', '3', '4', '5')"
                ),
                result.err,
            )
            self.assertEqual(self.tx(["show", "bad"]).code, 1)

    def test_t_eng_02_registry_get_and_registered(self):
        help_result = self.tx(["spawn", "--help"])
        self.assertEqual(help_result.code, 0)
        self.assertIn("--engine {claude,codex,antigravity}", help_result.out)
        record, dump = self.spawn("c", "--engine", "claude")
        self.assertEqual(os.path.basename(dump["argv"][0]), "claude")
        self.assertEqual(record["engine"], "claude")
        record, dump = self.spawn("x", "--engine", "codex")
        self.assertEqual(os.path.basename(dump["argv"][0]), "codex")
        self.assertEqual(record["engine"], "codex")
        result = self.tx(["spawn", "b", "--tag", "t", "--engine", "bogus", "--cwd", self.repo])
        self.assertEqual(result.code, 2)
        self.assertIn("tx spawn: error: argument --engine: invalid choice: 'bogus'", result.err)

    def test_t_eng_03_engine_for_command_by_first_token_basename(self):
        record, dump = self.spawn("m1", "--cmd", "codex -m x")
        self.assertEqual(record["engine"], "codex")
        self.assertEqual(record["role"], "llm")
        self.assertTrue(record["cwd"].startswith(str(self.home.worktrees_dir)), record["cwd"])
        fake_claude = str(self.fakes.bin_dir / "claude")
        record, dump = self.spawn("m2", "--cmd", f"{fake_claude} --model opus")
        self.assertEqual(record["engine"], "claude")
        self.assertEqual(record["role"], "llm")
        self.assertEqual(dump["argv"][0], fake_claude)
        result = self.tx(["spawn", "m3", "--tag", "t", "--cwd", self.repo, "--cmd", "bash"])
        self.assertEqual(result.code, 0, result.err)
        record = self.show("m3")
        self.assertNotIn("engine", record)
        self.assertEqual(record["role"], "shell")
        self.assertEqual(record["cwd"], self.repo)
        result = self.tx(["spawn", "m4", "--tag", "t", "--cwd", self.repo, "--cmd", "env X=1 claude"])
        self.assertEqual(result.code, 0, result.err)
        record = self.show("m4")
        self.assertNotIn("engine", record)
        self.assertEqual(record["role"], "other")
        self.assertEqual(record["cwd"], self.repo)

    def test_t_eng_03_explicit_engine_wins_and_missing_shim_names_inferred_engine(self):
        record, dump = self.spawn("m5", "--engine", "claude", "--cmd", "codex -m x", fake="codex")
        self.assertEqual(record["engine"], "claude")
        self.assertEqual(argv_of(dump), ["codex", "-m", "x"])
        (self.home.hooks_dir / "claude" / "start.sh").unlink()
        result = self.tx(["spawn", "m6", "--tag", "t", "--cwd", self.repo, "--cmd", "claude --model x"])
        self.assertEqual(result.code, 1)
        self.assertTrue(
            result.err.startswith(f"tx spawn: claude hooks are not installed in {self.home.path} — "),
            result.err,
        )
        self.assertEqual(self.tx(["show", "m6"]).code, 1)

    # ----- claude adapter — launch -------------------------------------------------------------

    def test_t_eng_10_claude_build_launch_command_defaults(self):
        record, dump = self.spawn("c", "--engine", "claude")
        expected = ["claude", "--effort", "high", "--no-chrome", CLAUDE_YOLO]
        self.assertEqual(argv_of(dump), expected)
        self.assertEqual(record["cmd"], shlex.join(expected))
        self.assertEqual(dump["env"]["TX_SESSION_ID"], record["id"])
        self.assertEqual(dump["env"]["TX_REQUIRE_WORKTREE"], "1")
        self.assertNotIn("TX_READ_ONLY", dump["env"])
        self.assertEqual(record["env"], {"TX_REQUIRE_WORKTREE": "1"})

    def test_t_eng_11_claude_launch_with_model_effort_prompt_browser_priming(self):
        record, dump = self.spawn(
            "c", "--engine", "claude", "--model", "opus", "--effort", "2", "--prompt", "go", "--chrome", "--role", "roleP"
        )
        expected = [
            "claude", "--model", "opus", "--effort", "medium", "--chrome",
            "--append-system-prompt", "C\n\nP", CLAUDE_YOLO, "go",
        ]
        self.assertEqual(argv_of(dump), expected)
        self.assertEqual(record["cmd"], shlex.join(expected))
        for effort, tier in ((1, "low"), (4, "xhigh"), (5, "max")):
            _, dump = self.spawn(f"e{effort}", "--engine", "claude", "--effort", str(effort))
            self.assertEqual(dump["argv"][dump["argv"].index("--effort") + 1], tier)
        _, dump = self.spawn("nochrome", "--engine", "claude", "--model", "opus")
        self.assertIn("--no-chrome", dump["argv"])
        self.assertNotIn("--chrome", dump["argv"])

    def test_t_eng_12_claude_read_only_launch_shape(self):
        record, dump = self.spawn("c", "--engine", "claude", "--read-only", "--prompt", "go")
        expected = ["claude", "--effort", "high", "--no-chrome", *CLAUDE_RO_BLOCK, "go"]
        self.assertEqual(record["cmd"], shlex.join(expected))
        self.assertNotIn(CLAUDE_YOLO, record["cmd"])
        self.assertEqual(argv_of(dump), expected)
        self.assertEqual(record["env"], {"TX_READ_ONLY": "1"})
        bwrap = self.fakes.wait_dump("bwrap", record["id"])
        self.assertEqual(bwrap["argv"][bwrap["argv"].index("--") + 1 :][1:], expected[1:])

    def test_t_eng_13_claude_distiller_command(self):
        self.addCleanup(self.reap_watchers)
        source_id, chat_id = self.source(
            "s", "claude --model opus --effort high --no-chrome --append-system-prompt P --dangerously-skip-permissions",
            chat="c1", transcript='{"type":"user"}\n',
        )
        result = self.tx(["handover", "s", "Fix it"])
        self.assertEqual(result.code, 0, result.err)
        op_id = self.only_op_id()
        record = self.show("s-handover-distill")
        self.assertEqual(record["tags"], ["temporary", "handover"])
        seed = self.handover_seed(source_id, chat_id, "Fix it", "fix-it", op_id)
        expected = ["claude", "--model", "opus", "--effort", "medium", "--no-chrome", CLAUDE_YOLO, seed]
        self.assertEqual(record["cmd"], shlex.join(expected))
        self.assertNotIn("--append-system-prompt", record["cmd"])
        dump = self.fakes.wait_dump("claude", record["id"])
        self.assertEqual(argv_of(dump), expected)

    def test_t_eng_13_codex_distiller_command(self):
        self.addCleanup(self.reap_watchers)
        source_id, chat_id = self.source("x", "codex -m o3 -c k=v", engine="codex", chat="r1")
        self.write_rollout(chat_id)
        result = self.tx(["handover", "x", "Fix it"])
        self.assertEqual(result.code, 0, result.err)
        op_id = self.only_op_id()
        record = self.show("x-handover-distill")
        seed = self.handover_seed(source_id, chat_id, "Fix it", "fix-it", op_id)
        expected = [*CODEX_DEFAULTS, *CODEX_YOLO, seed]
        self.assertEqual(record["cmd"], shlex.join(expected))
        dump = self.fakes.wait_dump("codex", record["id"])
        self.assertEqual(argv_of(dump), expected)

    # ----- claude adapter — _strip_identity grammar --------------------------------------------

    def assert_fork_argv(self, sources: dict[str, list[str]], *, prefix: list[str] | None = None) -> None:
        """For each `cmd` → `inherited`, craft S with that `cmd`, fork it, and assert the fake argv is
        `[claude, --resume, <chat>, --fork-session, *inherited, <yolo>]`."""
        for index, (cmd, inherited) in enumerate(sources.items()):
            name = f"s{index}"
            _, chat_id = self.source(name, cmd)
            _, dump = self.fork(name, f"{name}-fork")
            binary = prefix or ["claude"]
            self.assertEqual(
                argv_of(dump) if not prefix else dump["argv"],
                [*binary, "--resume", chat_id, "--fork-session", *inherited, CLAUDE_YOLO],
                cmd,
            )

    def test_t_eng_14_strip_identity_value_optional_bare_flags(self):
        self.assert_fork_argv(
            {
                "claude --session-id abc --model opus": ["--model", "opus"],
                "claude --resume abc --fork-session --model opus": ["--model", "opus"],
                "claude --resume --model opus": ["--model", "opus"],
                "claude -r abc -c --continue --tmux -w feat --worktree --from-pr 12": [],
                "": [],
            }
        )
        fake_claude = str(self.fakes.bin_dir / "claude")
        _, chat_id = self.source("sp", f"{fake_claude} --model x")
        _, dump = self.fork("sp", "sp-fork")
        self.assertEqual(dump["argv"], [fake_claude, "--resume", chat_id, "--fork-session", "--model", "x", CLAUDE_YOLO])

    def test_t_eng_14_resume_uses_the_same_grammar(self):
        _, chat_id = self.source("s", "claude --session-id abc --model opus")
        result = self.tx(["resume", "s"])
        self.assertEqual(result.code, 0, result.err)
        record = self.show("s")
        dump = self.fakes.wait_dump("claude", record["id"])
        self.assertEqual(argv_of(dump), ["claude", "--resume", chat_id, "--model", "opus", CLAUDE_YOLO])

    def test_t_eng_15_strip_keeps_unknown_value_flags_dangling_flags_variadics(self):
        self.assert_fork_argv(
            {
                'claude --unknown-flag val "prompt"': ["--unknown-flag", "val"],
                "claude --unknown-flag --model opus": ["--unknown-flag", "--model", "opus"],
                "claude --add-dir /a /b --model opus": ["--add-dir", "/a", "/b", "--model", "opus"],
                "claude --allowedTools Bash Read --model opus": ["--model", "opus"],
                'claude -p "prompt"': ["-p"],
                'claude --dangerously-skip-permissions "P"': [],
                'claude --append-system-prompt "multi word" --model opus': [
                    "--append-system-prompt", "multi word", "--model", "opus",
                ],
            }
        )

    def test_t_eng_16_strip_drops_positionals_golden(self):
        captured: list[list[str]] = []
        for index, cmd in enumerate(
            (
                'claude --model opus --effort high --no-chrome --dangerously-skip-permissions "long priming text"',
                'claude "prompt" --model opus',
            )
        ):
            name = f"s{index}"
            _, chat_id = self.source(name, cmd, chat=f"c{index}")
            _, dump = self.fork(name, f"{name}-fork")
            captured.append(argv_of(dump))
        self.assertEqual(
            captured[0],
            ["claude", "--resume", "c0", "--fork-session", "--model", "opus", "--effort", "high", "--no-chrome", CLAUDE_YOLO],
        )
        self.assertNotIn("long priming text", " ".join(captured[0]))
        self.assertEqual(captured[1], ["claude", "--resume", "c1", "--fork-session", "--model", "opus", CLAUDE_YOLO])
        self.assert_golden("eng/16", "".join(json.dumps(argv) + "\n" for argv in captured))

    def test_t_eng_17_strip_truncates_at_shell_control(self):
        self.assert_fork_argv(
            {
                "claude --model opus 'seed' && echo hi": ["--model", "opus"],
                "claude --model opus > out.log": ["--model", "opus"],
                "claude --model opus | tee x": ["--model", "opus"],
                "claude --model opus ; rm -rf /": ["--model", "opus"],
                'claude --unknown ">x"': ["--unknown"],
            }
        )

    def test_t_eng_18_claude_strip_access_flags(self):
        self.assert_fork_argv(
            {
                "claude --dangerously-skip-permissions --model x": ["--model", "x"],
                "claude --permission-mode dontAsk --x": ["--x"],
                "claude --setting-sources user": [],
                "claude --setting-sources project": ["--setting-sources", "project"],
                "claude --allowedTools Bash Read --disallowedTools Edit --model x": ["--model", "x"],
            }
        )

    def test_t_eng_19_claude_resume_fork_seed_command_exact_argv(self):
        src = 'claude --model opus --effort high --no-chrome --append-system-prompt P --dangerously-skip-permissions "seed"'
        persona = ["--model", "opus", "--effort", "high", "--no-chrome", "--append-system-prompt", "P"]

        _, chat_id = self.source("s0", "")
        self.tx(["resume", "s0"])
        record = self.show("s0")
        self.assertEqual(argv_of(self.fakes.wait_dump("claude", record["id"])), ["claude", "--resume", chat_id, CLAUDE_YOLO])

        source_id, chat_id = self.source("s", src, chat="c1", transcript='{"type":"user"}\n')
        result = self.tx(["resume", "s", "--as", "s-resumed"])
        self.assertEqual(result.code, 0, result.err)
        record = self.show("s-resumed")
        self.assertEqual(
            argv_of(self.fakes.wait_dump("claude", record["id"])),
            ["claude", "--resume", "c1", *persona, CLAUDE_YOLO],
        )
        _, dump = self.fork("s", "s-fork")
        self.assertEqual(argv_of(dump), ["claude", "--resume", "c1", "--fork-session", *persona, CLAUDE_YOLO])

        result = self.tx(["handover", "s", "t", "s-ho", "--self-catch-up"])
        self.assertEqual(result.code, 0, result.err)
        seed = self.self_catch_up_seed(source_id, "c1")
        record = self.show("s-ho")
        self.assertEqual(record["cmd"], shlex.join(["claude", *persona, CLAUDE_YOLO, seed]))
        self.assertEqual(argv_of(self.fakes.wait_dump("claude", record["id"])), ["claude", *persona, CLAUDE_YOLO, seed])

        result = self.tx(["handover", "s", "t", "s-ro", "--self-catch-up", "--read-only"])
        self.assertEqual(result.code, 0, result.err)
        record = self.show("s-ro")
        self.assertEqual(record["cmd"], shlex.join(["claude", *persona, *CLAUDE_RO_BLOCK, seed]))
        self.assertEqual(argv_of(self.fakes.wait_dump("claude", record["id"])), ["claude", *persona, *CLAUDE_RO_BLOCK, seed])

    def test_t_eng_19_resume_of_read_only_record_reapplies_the_block_once(self):
        ro_cmd = shlex.join(
            ["claude", "--model", "opus", "--effort", "high", "--no-chrome", "--append-system-prompt", "P", *CLAUDE_RO_BLOCK, "seed"]
        )
        _, chat_id = self.source("sro", ro_cmd, chat="c1", env={"TX_READ_ONLY": "1"}, transcript='{"a":1}\n')
        result = self.tx(["resume", "sro", "--as", "sro-2"])
        self.assertEqual(result.code, 0, result.err)
        record = self.show("sro-2")
        self.assertEqual(record["env"]["TX_READ_ONLY"], "1")
        # the whole persona is inherited — `--append-system-prompt P` included (NOTES: the spec's
        # list omits it); the inherited access flags are stripped and the RO block re-appended once
        argv = argv_of(self.fakes.wait_dump("claude", record["id"]))
        self.assertEqual(
            argv,
            ["claude", "--resume", "c1", "--model", "opus", "--effort", "high", "--no-chrome",
             "--append-system-prompt", "P", *CLAUDE_RO_BLOCK],
        )
        self.assertEqual(argv.count("--permission-mode"), 1)
        self.assertNotIn(CLAUDE_YOLO, argv)

    def test_t_eng_19_chrome_survives_into_all_three(self):
        source_id, chat_id = self.source("s", "claude --model opus --chrome --dangerously-skip-permissions")
        _, dump = self.fork("s", "s-fork")
        self.assertIn("--chrome", dump["argv"])
        self.tx(["resume", "s", "--as", "s-r"])
        self.assertIn("--chrome", self.fakes.wait_dump("claude", self.show("s-r")["id"])["argv"])
        self.tx(["handover", "s", "t", "s-h", "--self-catch-up"])
        self.assertIn("--chrome", self.fakes.wait_dump("claude", self.show("s-h")["id"])["argv"])

    def test_t_eng_20_claude_is_read_only_command(self):
        record, _ = self.spawn("c", "--engine", "claude", "--read-only")
        self.assertEqual(record["cmd"], shlex.join(["claude", "--effort", "high", "--no-chrome", *CLAUDE_RO_BLOCK]))
        _, chat_id = self.source(
            "sro",
            "claude --model opus --setting-sources project --allowedTools Bash --disallowedTools Edit Write NotebookEdit --permission-mode dontAsk --setting-sources user",
            chat="c1",
            env={"TX_READ_ONLY": "1"},
            transcript='{"a":1}\n',
        )
        before = self.git.worktrees()
        records_before = sorted(path.name for path in self.home.sessions_dir.iterdir())
        result = self.tx(["resume", "sro", "--as", "sro-2"])
        self.assertEqual(result.code, 1)
        self.assertEqual(result.err, "tx resume: claude command does not enforce the requested read-only mode\n")
        self.assertEqual(sorted(path.name for path in self.home.sessions_dir.iterdir()), records_before)
        self.assertEqual(self.git.worktrees(), before)

    # ----- claude adapter — transcripts, workspace, payloads -----------------------------------

    def test_t_eng_21_munge_and_transcript_sidecar_paths(self):
        _, chat_id = self.source("s", "claude --model opus", chat="c1", transcript='{"type":"user"}\n')
        result = self.tx(["resume", "s"])
        self.assertEqual(result.code, 0, result.err)
        record = self.show("s")
        worktree = record["cwd"]
        self.assertTrue(worktree.startswith(str(self.home.worktrees_dir)))
        munged = os.path.realpath(worktree).replace("/", "-").replace(".", "-")
        self.assertEqual(
            record["chats"][0]["transcript_path"],
            f"{self.home.claude_config_dir}/projects/{munged}/c1.jsonl",
        )
        self.assertEqual(
            self.home.claude_transcript_path("/home/u/proj.git", "x").parent.name, "-home-u-proj-git"
        )
        archive_id, _ = self.source("a", "claude --model opus", chat="c1", transcript='{"a":1}\n')
        sidecar = self.home.claude_transcript_path(self.repo, "c1").parent / "c1" / "tool-results"
        sidecar.mkdir(parents=True)
        (sidecar / "a.txt").write_text("A")
        result = self.tx(["archive", "a"])
        self.assertEqual(result.code, 0, result.err)
        bundle = self.home.history_dir / archive_id / "c1"
        self.assertEqual((bundle / "transcript.jsonl").read_text(), '{"a":1}\n')
        self.assertEqual((bundle / "tool-results" / "a.txt").read_text(), "A")

    def test_t_eng_21_symlinked_chat_cwd_still_ingests(self):
        link = self.root / "link"
        link.symlink_to(self.git.path)
        session_id, _ = self.source("s", "claude --model opus", chat="c1", chat_cwd=str(link))
        self.write_claude_transcript(str(link), "c1", '{"a":1}\n')
        self.assertIn(os.path.realpath(self.repo).replace("/", "-").replace(".", "-"), str(self.home.claude_transcript_path(str(link), "c1")))
        result = self.tx(["archive", "s"])
        self.assertEqual(result.code, 0, result.err)
        self.assertEqual(result.out, "Archived 's' (ingested 1 chat bundle(s))\n")
        self.assertTrue((self.home.history_dir / session_id / "c1" / "transcript.jsonl").is_file())

    def test_t_eng_21_claude_config_dir_unset_falls_back_to_home(self):
        _, chat_id = self.source("s", "claude --model opus", chat="c1")
        result = self.tx(["resume", "s"], env={"CLAUDE_CONFIG_DIR": None})
        self.assertEqual(result.code, 0, result.err)
        record = self.show("s")
        munged = os.path.realpath(record["cwd"]).replace("/", "-").replace(".", "-")
        self.assertEqual(
            record["chats"][0]["transcript_path"],
            f"{self.home.user_home}/.claude/projects/{munged}/c1.jsonl",
        )

    def test_t_eng_22_claude_bundle_paths_and_bundle_sidecars(self):
        session_id, _ = self.source("s", "claude --model opus", chat="c1", chat_cwd="/nope/gone")
        other = self.home.claude_config_dir / "projects" / "-other"
        (other / "c1" / "tool-results").mkdir(parents=True)
        (other / "c1.jsonl").write_text('{"x":1}\n{"x":2}\n')
        (other / "c1" / "tool-results" / "b.txt").write_text("B")
        result = self.tx(["archive", "s"])
        self.assertEqual(result.code, 0, result.err)
        bundle = self.home.history_dir / session_id / "c1"
        self.assertEqual((bundle / "transcript.jsonl").read_bytes(), (other / "c1.jsonl").read_bytes())
        self.assertEqual((bundle / "tool-results" / "b.txt").read_text(), "B")
        chats = self.tx(["chat", "ls", "s"])
        self.assertEqual(chats.code, 0, chats.err)
        self.assertTrue(chats.lines[1].endswith(f"   {bundle}"), chats.out)
        # resume stamps bundle_path on the NEW record before any ingest
        result = self.tx(["resume", "s", "--as", "s2"])
        self.assertEqual(result.code, 0, result.err)
        record = self.show("s2")
        self.assertEqual(record["chats"][0]["bundle_path"], str(self.home.history_dir / record["id"] / "c1"))
        self.assertFalse((self.home.history_dir / record["id"]).exists())

    def test_t_eng_23_claude_prepare_chat_for_cwd_copies_transcript_and_sidecars(self):
        text = '{"l":1}\n{"l":2}\n{"l":3}\n'
        _, chat_id = self.source("s", "claude --model opus", chat="c1", transcript=text)
        source_sidecar = self.home.claude_transcript_path(self.repo, "c1").parent / "c1" / "tool-results"
        source_sidecar.mkdir(parents=True)
        (source_sidecar / "a.txt").write_text("A")
        record, dump = self.fork("s", "s-fork")
        target = self.home.claude_transcript_path(record["cwd"], "c1")
        self.assertEqual(target.read_text(), text)
        self.assertEqual((target.parent / "c1" / "tool-results" / "a.txt").read_text(), "A")
        self.assertEqual(self.home.claude_transcript_path(self.repo, "c1").read_text(), text)
        self.assertEqual((source_sidecar / "a.txt").read_text(), "A")
        self.assertLessEqual(target.stat().st_ctime, dump["at"])
        # `tx resume S --as other` copies the same way
        result = self.tx(["resume", "s", "--as", "other"])
        self.assertEqual(result.code, 0, result.err)
        other = self.show("other")
        self.assertEqual(self.home.claude_transcript_path(other["cwd"], "c1").read_text(), text)

    def test_t_eng_23_edges(self):
        projects = self.home.claude_config_dir / "projects"
        # resume into the SAME linked worktree (name reused) → nothing copied
        linked = str(self.git.as_linked_worktree("same"))
        _, _ = self.source("same", "claude --model opus", chat="c1", cwd=linked, transcript='{"a":1}\n')
        before = sorted(path.name for path in projects.iterdir())
        result = self.tx(["resume", "same"])
        self.assertEqual(result.code, 0, result.err)
        self.assertEqual(self.show("same")["cwd"], linked)
        self.assertEqual(sorted(path.name for path in projects.iterdir()), before)
        # source transcript absent → no target project dir, spawn proceeds, resume warns
        _, _ = self.source("absent", "claude --model opus", chat="c2")
        result = self.tx(["resume", "absent"])
        self.assertEqual(result.code, 0, result.err)
        record = self.show("absent")
        self.assertFalse(self.home.claude_transcript_path(record["cwd"], "c2").parent.exists())
        self.assertIn("tx resume: warning — transcript for chat c2 not found under", result.err)
        # sidecar absent → only the transcript copied
        _, _ = self.source("nosidecar", "claude --model opus", chat="c3", transcript='{"a":1}\n')
        record, _ = self.fork("nosidecar", "nosidecar-fork")
        target = self.home.claude_transcript_path(record["cwd"], "c3")
        self.assertTrue(target.is_file())
        self.assertFalse((target.parent / "c3").exists())
        # pre-existing target sidecar file → merged
        _, _ = self.source("merge", "claude --model opus", chat="c4", transcript='{"a":1}\n')
        source_sidecar = self.home.claude_transcript_path(self.repo, "c4").parent / "c4" / "tool-results"
        source_sidecar.mkdir(parents=True)
        (source_sidecar / "a.txt").write_text("A")
        target_sidecar = self.home.claude_transcript_path(str(self.worktree_for("merge-fork")), "c4").parent / "c4" / "tool-results"
        target_sidecar.mkdir(parents=True)
        (target_sidecar / "z.txt").write_text("Z")
        record, _ = self.fork("merge", "merge-fork")
        self.assertEqual(record["cwd"], str(self.worktree_for("merge-fork")))
        self.assertEqual(sorted(path.name for path in target_sidecar.iterdir()), ["a.txt", "z.txt"])

    def test_t_eng_24_claude_prepare_workspace_links_skills(self):
        record, dump = self.spawn("c", "--engine", "claude", "--env", "TX_SKILLS=foo")
        self.assertEqual(record["cmd"], shlex.join(["claude", "--effort", "high", "--no-chrome", CLAUDE_YOLO]))
        link = Path(record["cwd"]) / ".claude" / "skills" / "foo"
        self.assertTrue(link.is_symlink())
        self.assertEqual(os.readlink(link), str(self.home.agents / "skills" / "foo"))
        self.assertIn(".claude/skills/", self.exclude_lines())
        self.assertEqual(dump["env"]["TX_SKILLS"], "foo")
        self.assertEqual(record["env"]["TX_SKILLS"], "foo")
        (self.home.agents / "roleP.md").write_text("---\nskills: [foo]\n---\nP\n")
        record, dump = self.spawn("r", "--engine", "claude", "--role", "roleP")
        self.assertTrue((Path(record["cwd"]) / ".claude" / "skills" / "foo").is_symlink())
        self.assertEqual(dump["env"]["TX_SKILLS"], "foo")

    def test_t_eng_24_resume_relinks_without_duplicating_the_exclude_line(self):
        record, _ = self.spawn("c", "--engine", "claude", "--env", "TX_SKILLS=foo")
        payload = json.dumps({"session_id": "c1", "transcript_path": "/p/c1.jsonl"})
        self.tx(["hook", "session-start"], env={"TX_SESSION_ID": record["id"]}, stdin=payload)
        self.assertEqual(self.tx(["kill", "c"]).code, 0)
        link = Path(record["cwd"]) / ".claude" / "skills" / "foo"
        link.unlink()
        link.symlink_to("/elsewhere")
        result = self.tx(["resume", "c"])
        self.assertEqual(result.code, 0, result.err)
        self.assertEqual(self.show("c")["cwd"], record["cwd"])
        self.assertEqual(os.readlink(link), str(self.home.agents / "skills" / "foo"))
        self.assertEqual(self.exclude_lines().count(".claude/skills/"), 1)

    def test_t_eng_24_empty_grant_and_common_grant(self):
        record, _ = self.spawn("none", "--engine", "claude", "--env", "TX_SKILLS=")
        self.assertFalse((Path(record["cwd"]) / ".claude" / "skills").exists())
        self.assertNotIn(".claude/skills/", self.exclude_lines())
        (self.home.agents / "COMMON.md").write_text("---\nskills: [foo]\n---\nC\n")
        record, _ = self.spawn("common", "--cmd", "claude --model x")
        self.assertNotIn("TX_SKILLS", record["env"])
        self.assertTrue((Path(record["cwd"]) / ".claude" / "skills" / "foo").is_symlink())

    def test_t_eng_24_parity_unknown_skill_refuses_the_spawn(self):
        before = self.git.worktrees()
        result = self.tx(["spawn", "bad", "--tag", "t", "--cwd", self.repo, "--engine", "claude", "--env", "TX_SKILLS=nope"])
        self.assertEqual(result.code, 1)
        self.assertIn("unknown skill 'nope'", result.err)
        self.assertEqual(self.tx(["show", "bad"]).code, 1)
        self.assertEqual(self.git.worktrees(), before)

    @expected_failure_on_python
    def test_t_eng_24_fixed_unknown_skill_has_no_traceback(self):
        result = self.tx(["spawn", "bad", "--tag", "t", "--cwd", self.repo, "--engine", "claude", "--env", "TX_SKILLS=nope"])
        self.assertEqual(result.code, 1)
        self.assertIn("unknown skill 'nope'", result.err)
        self.assertNotIn("Traceback", result.err)

    def test_t_eng_25_claude_capture_session_id_and_event_to_state(self):
        session_id = self.records.llm(name="s", state="idle")
        env = {"TX_SESSION_ID": session_id}
        payload = json.dumps({"session_id": "u1", "transcript_path": "/p/u1.jsonl", "hook_event_name": "SessionStart"})
        result = self.tx(["hook", "session-start"], env=env, stdin=payload)
        self.assertEqual(result.code, 0)
        record = self.records.load(session_id)
        self.assertEqual(record["chats"][0]["id"], "u1")
        self.assertEqual(record["chats"][0]["transcript_path"], "/p/u1.jsonl")
        self.assertEqual(record["state"], "idle")
        # missing session_id → pending stays; re-fired with another id → unchanged
        pending_id = self.records.llm(name="p", state="idle")
        self.tx(["hook", "session-start"], env={"TX_SESSION_ID": pending_id}, stdin=json.dumps({"transcript_path": "/p"}))
        self.assertIsNone(self.records.load(pending_id)["chats"][0]["id"])
        self.tx(["hook", "session-start"], env=env, stdin=json.dumps({"session_id": "u1x", "transcript_path": "/x"}))
        self.assertEqual(self.records.load(session_id)["chats"][0]["id"], "u1")
        self.assertEqual(self.records.load(session_id)["chats"][0]["transcript_path"], "/p/u1.jsonl")
        # prompt-submit captures AND transitions
        self.tx(["hook", "prompt-submit"], env={"TX_SESSION_ID": pending_id}, stdin=payload.replace("u1", "u2"))
        record = self.records.load(pending_id)
        self.assertEqual(record["chats"][0]["id"], "u2")
        self.assertEqual(record["state"], "working")

    def test_t_eng_25_event_to_state_table(self):
        session_id = self.records.llm(name="s", state="idle")
        env = {"TX_SESSION_ID": session_id}
        transitions = [
            ("prompt-submit", None, "working"),
            ("stop", None, "waiting"),
            ("working", None, "working"),
            ("session-end", None, "idle"),
            ("prompt-submit", None, "working"),
            ("notification", '{"notification_type":"idle_prompt"}', "waiting"),
            ("working", None, "working"),
            ("notification", '{"notification_type":"permission_prompt"}', "waiting"),
            ("working", None, "working"),
            ("notification", '{"notification_type":"elicitation_dialog"}', "waiting"),
            ("notification", '{"notification_type":"auth_success"}', "waiting"),
        ]
        expected_log = []
        for event, payload, state in transitions:
            before = self.records.load(session_id)["state"]
            result = self.tx(["hook", event], env=env, stdin=payload)
            self.assertEqual(result.code, 0)
            self.assertEqual(self.records.load(session_id)["state"], state, event)
            if state != before:
                expected_log.append(("state", f"s → {state}"))
        self.assertEqual([(line["type"], line["msg"]) for line in self.log_lines()], expected_log)

    # ----- codex adapter -----------------------------------------------------------------------

    def write_codex_config(self, directory: Path, text: str) -> None:
        directory.mkdir(parents=True, exist_ok=True)
        (directory / "config.toml").write_text(text)

    def developer_instructions(self, dump: dict) -> str:
        argv = dump["argv"]
        pairs = [argv[index + 1] for index, token in enumerate(argv) if token == "-c"]
        values = [pair.removeprefix("developer_instructions=") for pair in pairs if pair.startswith("developer_instructions=")]
        self.assertEqual(len(values), 1, argv)
        return values[0]

    def test_t_eng_30_codex_home_precedence(self):
        launch_home = self.root / "l"
        process_home = self.root / "p"
        user_home = self.root / "h"
        self.write_codex_config(launch_home, 'developer_instructions = "L"\n')
        self.write_codex_config(process_home, 'developer_instructions = "Proc"\n')
        self.write_codex_config(user_home / ".codex", 'developer_instructions = "H"\n')
        _, dump = self.spawn(
            "x1", "--engine", "codex", "--role", "roleP", "--env", f"CODEX_HOME={launch_home}",
            env={"CODEX_HOME": str(process_home)},
        )
        self.assertEqual(self.developer_instructions(dump), "L\n\nC\n\nP")
        _, dump = self.spawn(
            "x2", "--engine", "codex", "--role", "roleP", "--env", "CODEX_HOME=", "--env", f"HOME={user_home}",
            env={"CODEX_HOME": str(process_home)},
        )
        self.assertEqual(self.developer_instructions(dump), "H\n\nC\n\nP")
        _, dump = self.spawn("x3", "--engine", "codex", "--role", "roleP", env={"CODEX_HOME": str(process_home)})
        self.assertEqual(self.developer_instructions(dump), "Proc\n\nC\n\nP")
        _, dump = self.spawn(
            "x4", "--engine", "codex", "--role", "roleP", "--env", f"HOME={user_home}", env={"CODEX_HOME": None}
        )
        self.assertEqual(self.developer_instructions(dump), "H\n\nC\n\nP")

    def test_t_eng_31_codex_build_launch_command_defaults_and_effort(self):
        record, dump = self.spawn("x", "--engine", "codex")
        expected = [*CODEX_DEFAULTS, *CODEX_YOLO]
        self.assertEqual(argv_of(dump), expected)
        self.assertEqual(record["cmd"], shlex.join(expected))
        _, dump = self.spawn("x5", "--engine", "codex", "--effort", "5")
        self.assertIn("model_reasoning_effort=max", dump["argv"])
        _, dump = self.spawn("x1", "--engine", "codex", "--effort", "1")
        self.assertIn("model_reasoning_effort=low", dump["argv"])
        result = self.tx(["spawn", "x6", "--tag", "t", "--cwd", self.repo, "--engine", "codex", "--effort", "6"])
        self.assertEqual(result.code, 2)
        _, dump = self.spawn("xm", "--engine", "codex", "--model", "o3")
        self.assertEqual(dump["argv"][1:3], ["-m", "o3"])
        _, dump = self.spawn("xc", "--engine", "codex", "--chrome")
        self.assertEqual(argv_of(dump), expected)
        _, dump = self.spawn("xp", "--engine", "codex", "--prompt", "go")
        self.assertEqual(argv_of(dump), [*expected, "go"])

    def test_t_eng_32_codex_role_priming_merges_configured_developer_instructions(self):
        codex_home = self.root / "cx"
        self.write_codex_config(codex_home, 'developer_instructions = "Base"\n')
        record, dump = self.spawn("x", "--engine", "codex", "--role", "roleP", "--env", f"CODEX_HOME={codex_home}")
        self.assertEqual(
            argv_of(dump),
            [*CODEX_DEFAULTS, "-c", "developer_instructions=Base\n\nC\n\nP", *CODEX_YOLO],
        )
        variants = {
            "none": None,
            "invalid": "this is = not [toml\n",
            "blank": 'developer_instructions = "  "\n',
            "nonstring": "developer_instructions = 3\n",
        }
        for name, text in variants.items():
            directory = self.root / f"cx-{name}"
            directory.mkdir()
            if text is not None:
                self.write_codex_config(directory, text)
            _, dump = self.spawn(f"x-{name}", "--engine", "codex", "--role", "roleP", "--env", f"CODEX_HOME={directory}")
            self.assertEqual(self.developer_instructions(dump), "C\n\nP", name)

    def test_t_eng_33_codex_read_only_launch(self):
        record, dump = self.spawn("x", "--engine", "codex", "--read-only", "--prompt", "go")
        expected = [*CODEX_DEFAULTS, *CODEX_RO_BLOCK, "go"]
        self.assertEqual(record["cmd"], shlex.join(expected))
        self.assertNotIn("--dangerously-bypass-approvals-and-sandbox", record["cmd"])
        self.assertEqual(argv_of(dump), expected)
        self.assertEqual(record["env"], {"TX_READ_ONLY": "1"})

    def test_t_eng_34_codex_strip_identity_grammar(self):
        sources = {
            "codex resume abc -m x": ["-m", "x"],
            "codex fork abc --last -m x": ["-m", "x"],
            "codex resume --last --all --include-non-interactive": [],
            "codex resume": [],
            'codex --oss -m x "prompt"': ["--oss", "-m", "x"],
            "codex -c k=v -m x": ["-c", "k=v", "-m", "x"],
            "codex -i a.png b.png -m x": ["-i", "a.png", "b.png", "-m", "x"],
            'codex --unknown v "p"': ["--unknown", "v"],
            "codex --unknown --search": ["--unknown", "--search"],
            'codex --search "p" | tee x': ["--search"],
        }
        for index, (cmd, inherited) in enumerate(sources.items()):
            name = f"x{index}"
            _, chat_id = self.source(name, cmd, engine="codex", chat=f"r{index}")
            _, dump = self.fork(name, f"{name}-fork")
            self.assertEqual(argv_of(dump), ["codex", "fork", chat_id, *inherited, *CODEX_YOLO], cmd)

    def test_t_eng_35_codex_resume_fork_seed_distiller(self):
        self.addCleanup(self.reap_watchers)
        src = 'codex -m gpt-5.6-sol -c model_reasoning_effort=high --dangerously-bypass-approvals-and-sandbox --dangerously-bypass-hook-trust "seed"'
        persona = ["-m", "gpt-5.6-sol", "-c", "model_reasoning_effort=high"]
        _, chat_id = self.source("x0", "", engine="codex", chat="r0")
        self.write_rollout("r0")
        self.assertEqual(self.tx(["resume", "x0"]).code, 0)
        self.assertEqual(argv_of(self.fakes.wait_dump("codex", self.show("x0")["id"])), ["codex", "resume", "r0", *CODEX_YOLO])

        source_id, _ = self.source("x", src, engine="codex", chat="r1")
        self.write_rollout("r1")
        self.assertEqual(self.tx(["resume", "x", "--as", "x-r"]).code, 0)
        self.assertEqual(
            argv_of(self.fakes.wait_dump("codex", self.show("x-r")["id"])),
            ["codex", "resume", "r1", *persona, *CODEX_YOLO],
        )
        _, dump = self.fork("x", "x-fork")
        self.assertEqual(argv_of(dump), ["codex", "fork", "r1", *persona, *CODEX_YOLO])

        seed = self.self_catch_up_seed(source_id, "r1")
        self.assertEqual(self.tx(["handover", "x", "t", "x-ho", "--self-catch-up"]).code, 0)
        self.assertEqual(self.show("x-ho")["cmd"], shlex.join(["codex", *persona, *CODEX_YOLO, seed]))
        self.assertEqual(self.tx(["handover", "x", "t", "x-ro", "--self-catch-up", "--read-only"]).code, 0)
        self.assertEqual(self.show("x-ro")["cmd"], shlex.join(["codex", *persona, *CODEX_RO_BLOCK, seed]))

        result = self.tx(["handover", "x", "t", "x-d"])
        self.assertEqual(result.code, 0, result.err)
        op_id = self.only_op_id()
        distiller = self.show("x-d-distill")
        distill_seed = self.handover_seed(source_id, "r1", "t", "t", op_id)
        self.assertEqual(distiller["cmd"], shlex.join([*CODEX_DEFAULTS, *CODEX_YOLO, distill_seed]))

    def test_t_eng_35_sandbox_pair_in_source_stripped_before_destination_mode(self):
        source_id, _ = self.source("x", "codex -m x --sandbox read-only -a never", engine="codex", chat="r1")
        self.assertEqual(self.tx(["handover", "x", "t", "x-ro", "--self-catch-up", "--read-only"]).code, 0)
        argv = self.fakes.wait_dump("codex", self.show("x-ro")["id"])["argv"]
        self.assertEqual(argv.count("--sandbox"), 1)
        self.assertEqual(argv.count("--ask-for-approval"), 1)
        self.assertNotIn("-a", argv)
        self.assertNotIn("read-only", argv)
        self.assertEqual(argv[1:-1], ["-m", "x", *CODEX_RO_BLOCK])

    def test_t_eng_37_codex_resolve_transcript_via_recursive_rollout_glob(self):
        source_id, _ = self.source("x", "codex -m x", engine="codex", chat="r1")
        rollout = self.write_rollout("r1", text='{"r":1}\n')
        result = self.tx(["resume", "x"])
        self.assertEqual(result.code, 0, result.err)
        self.assertEqual(result.err, "")
        self.assertEqual(self.show("x")["chats"][0]["transcript_path"], str(rollout))
        self.assertEqual(self.tx(["archive", source_id]).code, 0)
        self.assertEqual((self.home.history_dir / source_id / "r1" / "transcript.jsonl").read_text(), '{"r":1}\n')

    def test_t_eng_37_two_matches_prefer_the_lexicographically_last(self):
        self.source("x", "codex -m x", engine="codex", chat="r2")
        self.write_rollout("r2", date_dir="2026/09/16")
        later = self.write_rollout("r2", date_dir="2026/09/17")
        self.assertEqual(self.tx(["resume", "x"]).code, 0)
        self.assertEqual(self.show("x")["chats"][0]["transcript_path"], str(later))

    def test_t_eng_37_no_match_gives_the_sentinel_and_the_warning(self):
        self.source("x", "codex -m x", engine="codex", chat="r3")
        result = self.tx(["resume", "x"])
        self.assertEqual(result.code, 0, result.err)
        self.assertEqual(
            result.err,
            f"tx resume: warning — transcript for chat r3 not found under {self.repo}; claude --resume may start a fresh conversation\n",
        )
        sentinel = self.home.codex_home / "sessions" / "rollout-r3.jsonl"
        self.assertEqual(self.show("x")["chats"][0]["transcript_path"], str(sentinel))
        self.assertFalse(sentinel.exists())

    def test_t_eng_38_codex_prepare_workspace_skills_and_non_standalone_passthrough(self):
        record, dump = self.spawn("x", "--engine", "codex", "--env", "TX_SKILLS=foo")
        self.assertEqual(argv_of(dump), [*CODEX_DEFAULTS, *CODEX_YOLO])
        self.assertNotIn("check_for_update_on_startup=false", dump["argv"])
        link = Path(record["cwd"]) / ".agents" / "skills" / "foo"
        self.assertEqual(os.readlink(link), str(self.home.agents / "skills" / "foo"))
        self.assertIn(".agents/skills/", self.exclude_lines())
        self.assertFalse((self.home.path / "codex-update").exists())
        record, dump = self.spawn("y", "--cmd", "codex -m x | tee /dev/null", "--env", "TX_SKILLS=foo")
        self.assertEqual(record["cmd"], "codex -m x | tee /dev/null")
        self.assertTrue((Path(record["cwd"]) / ".agents" / "skills" / "foo").is_symlink())

    # ----- codex standalone update ------------------------------------------------------------

    def standalone_layout(
        self, label: str, *, link_target: str = "current/bin/codex", executable_symlink: bool = True,
        current_is_dir: bool = False, current_target: str = "releases/1.0",
    ) -> tuple[Path, Path]:
        """Build `<root>/<label>/cx` (CODEX_HOME) + `<root>/<label>/bin` (PATH head) per the spec's
        layout; returns (codex_home, bin_dir). The fake codex is copied to `releases/1.0/bin/codex`
        and `releases/1.0/codex`."""
        base = self.root / label
        codex_home = base / "cx"
        release = codex_home / "packages" / "standalone" / "releases" / "1.0"
        (release / "bin").mkdir(parents=True)
        fake = self.fakes.bin_dir / "codex"
        shutil.copy2(fake, release / "bin" / "codex")
        shutil.copy2(fake, release / "codex")
        current = codex_home / "packages" / "standalone" / "current"
        if current_is_dir:
            shutil.copytree(release, current)
        else:
            current.symlink_to(current_target)
        bin_dir = base / "bin"
        bin_dir.mkdir()
        if executable_symlink:
            (bin_dir / "codex").symlink_to(codex_home / "packages" / "standalone" / link_target)
        else:
            shutil.copy2(fake, bin_dir / "codex")
        curl = bin_dir / "curl"
        curl.write_text(CURL_STUB)
        curl.chmod(0o755)
        (self.root / "elsewhere").mkdir(exist_ok=True)
        shutil.copy2(fake, self.root / "elsewhere" / "codex")
        return codex_home, bin_dir

    def standalone_env(self, bin_dir: Path, **extra: str) -> dict[str, str]:
        base = self.tx_env()
        env = {"PATH": f"{bin_dir}{os.pathsep}{base['PATH']}", "CURL_STUB_OUT": str(self.root / "curl-out")}
        env.update(extra)
        return env

    def curl_dumps(self) -> list[dict]:
        directory = self.root / "curl-out"
        if not directory.is_dir():
            return []
        return [json.loads(path.read_text()) for path in sorted(directory.iterdir())]

    def update_log(self) -> Path:
        return self.home.path / "codex-update" / "update.log"

    def test_t_eng_39_codex_standalone_executable_detection(self):
        codex_home, bin_dir = self.standalone_layout("a")
        record, dump = self.spawn("x", "--engine", "codex", "--env", f"CODEX_HOME={codex_home}", env=self.standalone_env(bin_dir))
        self.assertEqual(dump["argv"][1:3], UPDATE_CHECK_TOKENS)
        self.assertEqual(record["cmd"], shlex.join(["codex", *UPDATE_CHECK_TOKENS, *CODEX_DEFAULTS[1:], *CODEX_YOLO]))
        self.assertTrue(self.update_log().is_file())
        self.wait_until(lambda: "Update succeeded" in self.update_log().read_text(), timeout=20)
        codex_home, bin_dir = self.standalone_layout("nobin", link_target="current/codex")
        _, dump = self.spawn("x-nobin", "--engine", "codex", "--env", f"CODEX_HOME={codex_home}", env=self.standalone_env(bin_dir))
        self.assertEqual(dump["argv"][1:3], UPDATE_CHECK_TOKENS)

    def test_t_eng_39_not_detected_variants(self):
        shutil.rmtree(self.home.path / "codex-update", ignore_errors=True)
        variants = {
            "regular": dict(executable_symlink=False),
            "currentdir": dict(current_is_dir=True),
            "elsewhere": dict(link_target="../../../../elsewhere/codex"),
            "outside": dict(current_target="../../../elsewhere"),
        }
        for label, options in variants.items():
            codex_home, bin_dir = self.standalone_layout(label, **options)
            _, dump = self.spawn(f"x-{label}", "--engine", "codex", "--env", f"CODEX_HOME={codex_home}", env=self.standalone_env(bin_dir))
            self.assertNotIn("check_for_update_on_startup=false", dump["argv"], label)
            self.assertFalse((self.home.path / "codex-update").exists(), label)

    def test_t_eng_40_codex_disable_startup_update_check(self):
        codex_home, bin_dir = self.standalone_layout("a")
        rewrites = {
            "codex -m x": ["codex", *UPDATE_CHECK_TOKENS, "-m", "x"],
            "codex -c check_for_update_on_startup=true -m x": ["codex", *UPDATE_CHECK_TOKENS, "-m", "x"],
            "codex --config=check_for_update_on_startup=true": ["codex", *UPDATE_CHECK_TOKENS],
            "codex --config check_for_update_on_startup=true": ["codex", *UPDATE_CHECK_TOKENS],
            "codex -c other=1": ["codex", *UPDATE_CHECK_TOKENS, "-c", "other=1"],
        }
        for index, (cmd, expected) in enumerate(rewrites.items()):
            record, dump = self.spawn(
                f"x{index}", "--cmd", cmd, "--env", f"CODEX_HOME={codex_home}", env=self.standalone_env(bin_dir)
            )
            self.assertEqual(argv_of(dump), expected, cmd)
            self.assertEqual(record["cmd"], shlex.join(expected), cmd)

    def test_t_eng_41_codex_schedule_update_interval_flock_log(self):
        codex_home, bin_dir = self.standalone_layout("a")
        gate = self.root / "gate"
        env = self.standalone_env(bin_dir, CURL_STUB_GATE=str(gate))
        started = time.time()
        record, dump = self.spawn("x", "--engine", "codex", "--env", f"CODEX_HOME={codex_home}", env=env)
        log = self.update_log()
        first_line = log.read_text().splitlines()[0]
        self.assertRegex(first_line, r"^\[\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z\] Checking for Codex updates$")
        self.assertNotIn("Update succeeded", log.read_text())  # the child is still gated → spawn did not wait
        self.wait_until(self.curl_dumps, timeout=10)
        gate.write_text("")
        self.wait_until(lambda: "Update succeeded" in log.read_text(), timeout=20)
        self.assertEqual(log.read_text(), f"{first_line}\nok\nUpdate succeeded\n")
        curl_env = self.curl_dumps()[0]["env"]
        self.assertEqual(curl_env["CODEX_HOME"], str(codex_home))
        self.assertEqual(curl_env["CODEX_INSTALL_DIR"], str(bin_dir))
        self.assertEqual(curl_env["CODEX_NON_INTERACTIVE"], "1")
        # fresh log → second spawn leaves it byte-identical, no curl call
        content = log.read_bytes()
        self.spawn("x2", "--engine", "codex", "--env", f"CODEX_HOME={codex_home}", env=env)
        self.assertEqual(log.read_bytes(), content)
        self.assertEqual(len(self.curl_dumps()), 1)
        # 5 h old → truncated + rewritten header
        old = time.time() - 5 * 3600
        os.utime(log, (old, old))
        self.spawn("x3", "--engine", "codex", "--env", f"CODEX_HOME={codex_home}", env=self.standalone_env(bin_dir))
        self.wait_until(lambda: len(self.curl_dumps()) == 2, timeout=10)
        self.assertRegex(log.read_text().splitlines()[0], r"^\[\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z\] Checking for Codex updates$")
        self.assertGreater(log.stat().st_mtime, started)
        self.wait_until(lambda: "Update succeeded" in log.read_text(), timeout=20)
        # empty log with a fresh mtime → runs
        log.write_text("")
        self.spawn("x4", "--engine", "codex", "--env", f"CODEX_HOME={codex_home}", env=self.standalone_env(bin_dir))
        self.wait_until(lambda: len(self.curl_dumps()) == 3, timeout=10)
        self.wait_until(lambda: "Update succeeded" in log.read_text(), timeout=20)
        # another process holds the flock → spawn exit 0, log untouched, no curl, token still present
        holder = subprocess.Popen(["flock", "-x", str(log), "sleep", "10"])
        self.addCleanup(holder.wait)
        self.addCleanup(holder.kill)
        self.wait_until(lambda: subprocess.run(["flock", "-n", str(log), "true"]).returncode != 0)
        os.utime(log, (old, old))
        content = log.read_bytes()
        _, dump = self.spawn("x5", "--engine", "codex", "--env", f"CODEX_HOME={codex_home}", env=self.standalone_env(bin_dir))
        self.assertEqual(log.read_bytes(), content)
        self.assertEqual(len(self.curl_dumps()), 3)
        self.assertEqual(dump["argv"][1:3], UPDATE_CHECK_TOKENS)

    def test_t_eng_41_state_dir_is_a_regular_file(self):
        codex_home, bin_dir = self.standalone_layout("a")
        (self.home.path / "codex-update").write_text("not a dir")
        result = self.tx(
            ["spawn", "x", "--tag", "t", "--cwd", self.repo, "--engine", "codex", "--env", f"CODEX_HOME={codex_home}"],
            env=self.standalone_env(bin_dir),
        )
        self.assertEqual(result.code, 0, result.err)
        self.assertEqual(
            result.err,
            f"tx: could not schedule the Codex update check: [Errno 17] File exists: '{self.home.path / 'codex-update'}'; launching the current version\n",
        )
        record = self.show("x")
        self.assertEqual(self.fakes.wait_dump("codex", record["id"])["argv"][1:3], UPDATE_CHECK_TOKENS)

    def test_t_eng_42_codex_run_update_child_protocol(self):
        codex_home, bin_dir = self.standalone_layout("a")
        self.spawn("x", "--engine", "codex", "--env", f"CODEX_HOME={codex_home}", env=self.standalone_env(bin_dir))
        log = self.update_log()
        self.wait_until(lambda: "Update succeeded" in log.read_text(), timeout=20)
        argv = self.curl_dumps()[0]["argv"]
        self.assertEqual(argv[:7], ["-fsSL", "--connect-timeout", "10", "--max-time", "45", "https://chatgpt.com/codex/install.sh", "-o"])
        self.assertRegex(argv[7], r"/tx-codex-update-[^/]+/install\.sh$")
        self.assertEqual(len(argv), 8)
        lines = log.read_text().splitlines()
        self.assertEqual(lines[1:], ["ok", "Update succeeded"])

    def test_t_eng_42_curl_failure_is_logged_and_the_installer_does_not_run(self):
        codex_home, bin_dir = self.standalone_layout("a")
        self.spawn("x", "--engine", "codex", "--env", f"CODEX_HOME={codex_home}", env=self.standalone_env(bin_dir, CURL_STUB_FAIL="1"))
        log = self.update_log()
        self.wait_until(lambda: "Update failed" in log.read_text(), timeout=20)
        lines = log.read_text().splitlines()
        self.assertEqual(len(lines), 2)
        self.assertRegex(lines[1], r"^Update failed: Command '\['curl', '-fsSL'.*returned non-zero exit status 3\.$")
        self.assertNotIn("ok", lines)

    def test_t_eng_44_codex_capture_event_to_state_and_no_sidecars(self):
        session_id = self.records.llm(name="x", state="idle", engine="codex", chats=None)
        record = self.records.load(session_id)
        record["chats"][0]["engine"] = "codex"
        self.records.write(record)
        result = self.tx(
            ["hook", "prompt-submit", "--engine", "codex"],
            env={"TX_SESSION_ID": session_id},
            stdin=json.dumps({"session_id": "u2", "transcript_path": "/s/rollout-x-u2.jsonl"}),
        )
        self.assertEqual(result.code, 0)
        record = self.records.load(session_id)
        self.assertEqual(record["chats"][0]["id"], "u2")
        self.assertEqual(record["chats"][0]["transcript_path"], "/s/rollout-x-u2.jsonl")
        self.assertEqual(record["state"], "working")

        archive_id, _ = self.source("a", "codex -m x", engine="codex", chat="r1")
        rollout = self.write_rollout("r1", text='{"r":1}\n')
        sibling = rollout.parent / "r1" / "tool-results"
        sibling.mkdir(parents=True)
        (sibling / "x.txt").write_text("X")
        self.assertEqual(self.tx(["archive", "a"]).code, 0)
        bundle = self.home.history_dir / archive_id / "r1"
        self.assertEqual(sorted(path.name for path in bundle.iterdir()), [".ingest.lock", "transcript.jsonl"])

        self.source("s", "codex -m x", engine="codex", chat="r2")
        self.write_rollout("r2")
        projects = self.home.claude_config_dir / "projects"
        projects_before = sorted(str(path) for path in projects.rglob("*")) if projects.exists() else []
        codex_before = sorted(str(path) for path in self.home.codex_home.rglob("*"))
        self.assertEqual(self.tx(["resume", "s", "--as", "other"]).code, 0)
        self.assertEqual(sorted(str(path) for path in projects.rglob("*")) if projects.exists() else [], projects_before)
        self.assertEqual(sorted(str(path) for path in self.home.codex_home.rglob("*")), codex_before)
