"""Filesystem layout + the `Storage` sync-boundary abstraction (stage S0).

Two distinct concerns live here:

1. **The `$TX_IDE_HOME` layout** (tx-service-redesign.md §3, install-flip.md §2.3) — the single
   source of truth for where tx state lives on disk. `tx_ide_home()` resolves the home (C9: env
   var with a `~/.tx-ide` default); the `*_dir` / `*_path` helpers derive every subpath from it.
   `store.py`, `events.py`, and `claude.py` import these rather than re-deriving paths.

2. **The `Storage` interface** (§14) — a KV abstraction over string keys that wraps **only** the
   future `tx sync` copy boundary (S7), so the tree maps 1:1 to remote storage for a reproducible
   corpus. `LocalStorage` is the filesystem default; `S3Storage` is an S7 stub.

OPEN-0a (decided): **`SessionStore` is filesystem-direct and does NOT go through `Storage`.** Its
correctness rests on atomic `os.replace` + directory `glob`, which a KV `get/put` cannot preserve.
`store.py` imports only the `sessions_dir()` path helper from this module — never the `Storage`
class. Do not route record access through `Storage`.
"""

from __future__ import annotations

import os
from abc import ABC, abstractmethod
from pathlib import Path

# Default home, overridable via $TX_IDE_HOME. The dev home during the redesign build is
# ~/.tx-ide-next (coexistence — keeps the live bash tx on ~/.tx-ide untouched until Flip).
DEFAULT_HOME = "~/.tx-ide"


def tx_ide_home() -> Path:
    """Resolve `$TX_IDE_HOME` (default `~/.tx-ide`) — C9.

    Hooks run with a minimal environment and cannot rely on a shell rc, so the installer bakes the
    resolved home into each generated shim (install-flip §2.4); that bake is what makes the dev
    home work hook-driven. An exported `$TX_IDE_HOME` still overrides for one-off sandbox runs.
    """
    return Path(os.environ.get("TX_IDE_HOME", DEFAULT_HOME)).expanduser()


def sessions_dir() -> Path:
    """`$TX_IDE_HOME/sessions/` — canonical `<uuid>.json` records (`SessionStore`)."""
    return tx_ide_home() / "sessions"


def history_dir() -> Path:
    """`$TX_IDE_HOME/history/` — ingested chat bundles `<tx-id>/<chat-uuid>/` (§11, S3)."""
    return tx_ide_home() / "history"


def artifacts_dir() -> Path:
    """`$TX_IDE_HOME/artifacts/` — durable artifact records `<id>.json` (`ArtifactStore`) alongside
    each artifact's file directory `<id>/` (working copy + `revs/`). Records and content dirs share
    this parent; the store's `*.json` glob selects only records (Plan 2)."""
    return tx_ide_home() / "artifacts"


def worktrees_dir() -> Path:
    """`$TX_IDE_HOME/worktrees/` — tx-owned linked checkouts for agent sessions."""
    return tx_ide_home() / "worktrees"


def chat_ops_dir() -> Path:
    """`$TX_IDE_HOME/chat-ops/` — transient op-specs `<op-id>/` for in-flight handover/rollover.

    A handover/rollover writes its full spec here so the distiller triggers completion with one short
    verb (`tx _chat-op-finish <op-id>`) instead of echoing a long exact command, and a detached
    watchdog can finish the op deterministically if the distiller flakes (S4 reliability). Each op
    owns a directory so an atomic `claim/` mkdir gives the finish single-execution. Throwaway."""
    return tx_ide_home() / "chat-ops"


def log_path() -> Path:
    """`$TX_IDE_HOME/log.jsonl` — the single append-only provenance log (D8, `EventLog`)."""
    return tx_ide_home() / "log.jsonl"


def config_path() -> Path:
    """`$TX_IDE_HOME/config.json` — runtime config (§19)."""
    return tx_ide_home() / "config.json"


def agents_dir() -> Path:
    """`$TX_IDE_HOME/agents` — symlink to the repo's shipped role files (created by the installer)."""
    return tx_ide_home() / "agents"


def user_agents_dir() -> Path:
    """`$TX_IDE_HOME/user-agents/` — user role overrides."""
    return tx_ide_home() / "user-agents"


def hooks_dir() -> Path:
    """`$TX_IDE_HOME/hooks/` — the C9-baked hook shims (generated by `setup/engines/claude.sh`, S2)."""
    return tx_ide_home() / "hooks"


def launch_dir() -> Path:
    """`$TX_IDE_HOME/launch/` — per-session scripts for commands too large for tmux's client
    message (e.g. a role-primed agent launch)."""
    return tx_ide_home() / "launch"


def ensure_home() -> Path:
    """Create the `$TX_IDE_HOME` skeleton if absent (idempotent) and return the home path.

    Creates the directories foundation code writes into (`sessions/`, `history/`, `worktrees/`,
    `user-agents/`, `artifacts/`). `agents` (a symlink to the repo) and `hooks/` (baked shims) are
    the installer's job (S2), not created here. The full installer may call this or replicate it;
    `python3.14 -m tx _init-home` exposes it so the installer need not duplicate the layout.
    """
    home = tx_ide_home()
    for directory in (
        home,
        sessions_dir(),
        history_dir(),
        worktrees_dir(),
        user_agents_dir(),
        artifacts_dir(),
        launch_dir(),
    ):
        directory.mkdir(parents=True, exist_ok=True)
    return home


class Storage(ABC):
    """The `tx sync` copy boundary (§14) — NOT the record-access path (OPEN-0a).

    A key/value abstraction over string keys relative to `$TX_IDE_HOME`, so the whole tree
    (records + history bundles + `log.jsonl` + `config.json`) maps 1:1 to remote storage for a
    reproducible corpus. Introduced for `tx sync push/pull/status`; local stays the hot path.
    """

    @abstractmethod
    def get(self, key: str) -> bytes:
        """Read the bytes stored at `key`."""

    @abstractmethod
    def put(self, key: str, data: bytes) -> None:
        """Write `data` at `key`, creating intermediate containers as needed."""

    @abstractmethod
    def list(self, prefix: str = "") -> list[str]:
        """Every key under `prefix` (relative keys, sorted)."""

    @abstractmethod
    def delete(self, key: str) -> None:
        """Remove `key` (no error if absent)."""

    @abstractmethod
    def exists(self, key: str) -> bool:
        """Whether `key` is present."""


class LocalStorage(Storage):
    """Filesystem-backed `Storage`, rooted at `$TX_IDE_HOME` (the default working set, §14).

    Keys are paths relative to the root. This is the sync *source* — the reproducible local
    corpus that `S3Storage` (S7) will mirror to remote storage. It is NOT how records are accessed
    day to day; that is `SessionStore`, which is filesystem-direct (OPEN-0a).
    """

    def __init__(self, root: Path | None = None):
        self.root = root if root is not None else tx_ide_home()

    def _path(self, key: str) -> Path:
        return self.root / key

    def get(self, key: str) -> bytes:
        return self._path(key).read_bytes()

    def put(self, key: str, data: bytes) -> None:
        path = self._path(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)

    def list(self, prefix: str = "") -> list[str]:
        keys = [
            str(path.relative_to(self.root))
            for path in self.root.rglob("*")
            if path.is_file()
        ]
        return sorted(key for key in keys if key.startswith(prefix))

    def delete(self, key: str) -> None:
        self._path(key).unlink(missing_ok=True)

    def exists(self, key: str) -> bool:
        return self._path(key).exists()


class S3Storage(Storage):
    """Remote-storage stub — the real backend is deferred (§14).

    S7 wired the `tx sync` shape (the diff + last-writer-wins copy lives in `sync.py`) against the
    `Storage` interface and proved it end-to-end on `LocalStorage`; the S3 backend itself (the
    boto3-vs-`aws`-CLI decision and credentials) is still deferred, so every method raises a clean
    "deferred" error rather than half-working. `tx sync` catches it at the CLI boundary and prints
    the deferred message instead of a traceback.
    """

    def __init__(self, bucket: str, prefix: str = ""):
        self.bucket = bucket
        self.prefix = prefix

    def _unimplemented(self) -> NotImplementedError:
        return NotImplementedError(
            "S3 sync: deferred — the S3 backend is not implemented yet (§14). "
            "Use `--remote PATH` for a local archive, or configure it later."
        )

    def get(self, key: str) -> bytes:
        raise self._unimplemented()

    def put(self, key: str, data: bytes) -> None:
        raise self._unimplemented()

    def list(self, prefix: str = "") -> list[str]:
        raise self._unimplemented()

    def delete(self, key: str) -> None:
        raise self._unimplemented()

    def exists(self, key: str) -> bool:
        raise self._unimplemented()
