#!/usr/bin/env bash
# antigravity.sh {install|uninstall|status} [--dry-run]
#
# The Antigravity (`agy`) engine integration. Unlike claude.sh / codex.sh there is NO global hooks
# file to write: `~/.gemini/config/hooks.json` does not fire (refuted live on 1.1.12, both layout
# variants) — agy only discovers `.agents/hooks.json` at the workspace root. So this installer
# writes (1) the four tx hook shims and (2) a hooks.json TEMPLATE beside them; tx copies the
# template into each worker worktree's `.agents/hooks.json` at spawn time
# (lib/tx/engines/antigravity.py `prepare_workspace`).
set -euo pipefail

SCRIPT_DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -P "$SCRIPT_DIR/../.." && pwd)"
LIB_DIR="$REPO_ROOT/lib"
PY="${TX_PYTHON:-python3.14}"

# Expand a leading ~ by hand — env vars are not tilde-expanded.
TX_HOME="${TX_IDE_HOME:-$HOME/.tx-ide}"
TX_HOME="${TX_HOME/#\~/$HOME}"

B=$'\e[1m'; G=$'\e[32m'; Y=$'\e[33m'; RED=$'\e[31m'; D=$'\e[2m'; X=$'\e[0m'
ok()     { printf '  %s→%s %-46s %s%s%s\n' "$G" "$X" "$1" "$G" "${2:-ok}" "$X"; }
warn()   { printf '  %s→%s %-46s %s%s%s\n' "$Y" "$X" "$1" "$Y" "${2:-}" "$X"; }
info()   { printf '  %s%s%s\n' "$D" "$*" "$X"; }
header() { printf '\n%s%s%s\n' "$B" "$*" "$X"; }
die()    { printf '%santigravity.sh: %s%s\n' "$RED" "$*" "$X" >&2; exit 1; }

usage() {
  cat >&2 <<EOF
usage: antigravity.sh {install|uninstall|status} [--dry-run]

  install     write tx-ide's agy hook shims + the per-worktree hooks.json template
  uninstall   reverse it exactly — remove the shims + template
  status      report what is installed

  --dry-run   print every action, change nothing
EOF
}

OP=""; DRY_RUN=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    install|uninstall|status) OP="$1"; shift ;;
    --dry-run)        DRY_RUN=1; shift ;;
    -h|--help)        usage; exit 0 ;;
    *) printf 'antigravity.sh: unknown argument: %s\n' "$1" >&2; usage; exit 2 ;;
  esac
done
[[ -n "$OP" ]] || { usage; exit 2; }

# agy events fan in to these shims via the per-worktree hooks.json (copied from the template).
# SessionStart is undocumented but fires (verified live, 1.1.13); there is no permission event and
# no session-end event.
HOOKS_DIR="$TX_HOME/hooks/antigravity"
START_SHIM="$HOOKS_DIR/start.sh"     # SessionStart                              → session-start
PRE_SHIM="$HOOKS_DIR/pre.sh"         # PreInvocation                             → prompt-submit
WORK_SHIM="$HOOKS_DIR/work.sh"       # PreToolUse / PostToolUse / PostInvocation → working
POST_SHIM="$HOOKS_DIR/post.sh"       # Stop                                      → stop
TEMPLATE="$HOOKS_DIR/hooks.json.template"

write_shim() {  # <path> <subcommand>
  local path="$1" subcommand="$2"
  if [[ $DRY_RUN -eq 1 ]]; then
    info "would generate shim $path  ($subcommand --engine antigravity, home baked = $TX_HOME)"
    return 0
  fi
  mkdir -p "$(dirname "$path")"
  cat >"$path" <<EOF
#!/bin/bash
# tx-ide agy hook shim — GENERATED by setup/engines/antigravity.sh. Do NOT edit; re-run the
# installer to regenerate. \$TX_IDE_HOME and the package lib are baked in as literals because agy
# runs hooks with a minimal env (and cwd = the worktree's .agents/). stdin is left CONNECTED so
# \`tx hook\` can read conversationId/transcriptPath off the JSON payload (the universal capture
# path). agy parses hook stdout as a JSON reply; \`tx hook\` prints nothing, which agy treats as
# "no decision" (fail-open, verified).
exec env TX_IDE_HOME="$TX_HOME" PYTHONPATH="$LIB_DIR" "$PY" -m tx hook $subcommand --engine antigravity
EOF
  chmod +x "$path"
  ok "shim $path" "$subcommand"
}

remove_file() {  # <path> <label>
  local path="$1" label="${2:-$1}"
  if [[ $DRY_RUN -eq 1 ]]; then info "would remove $label"; return 0; fi
  if [[ -f "$path" ]]; then rm -f "$path"; ok "removed $label"; else info "$label (already absent)"; fi
}

write_template() {
  if [[ $DRY_RUN -eq 1 ]]; then
    info "would write template $TEMPLATE"
    return 0
  fi
  mkdir -p "$HOOKS_DIR"
  # The exact shapes agy 1.1.13 parses (builtin docs + verified live): tool events are GROUPED
  # (matcher + hooks wrapper), the rest are FLAT handler lists — mixing the shapes up makes agy
  # reject the whole file silently.
  TX_START="$START_SHIM" TX_PRE="$PRE_SHIM" TX_WORK="$WORK_SHIM" TX_POST="$POST_SHIM" \
  TX_TEMPLATE="$TEMPLATE" "$PY" - <<'PY'
import json, os

start, pre, work, post = (os.environ[key] for key in ("TX_START", "TX_PRE", "TX_WORK", "TX_POST"))
flat = lambda command: [{"type": "command", "command": command}]
grouped = lambda command: [{"matcher": "*", "hooks": [{"type": "command", "command": command}]}]
template = {"tx-ide": {
    "SessionStart": flat(start),
    "PreInvocation": flat(pre),
    "PreToolUse": grouped(work),
    "PostToolUse": grouped(work),
    "PostInvocation": flat(work),
    "Stop": flat(post),
}}
with open(os.environ["TX_TEMPLATE"], "w") as handle:
    json.dump(template, handle, indent=2)
    handle.write("\n")
PY
  ok "template $TEMPLATE"
}

cmd_install() {
  printf '%s== antigravity.sh install ==%s  %s\n' "$B" "$X" "$( ((DRY_RUN)) && echo '(dry-run)')"
  header "agy hook shims under $HOOKS_DIR (stdin kept, --engine antigravity)"
  write_shim "$START_SHIM" session-start
  write_shim "$PRE_SHIM"   prompt-submit
  write_shim "$WORK_SHIM"  working
  write_shim "$POST_SHIM"  stop

  header "per-worktree hooks.json template (copied into each worker's .agents/ at spawn)"
  write_template
}

cmd_uninstall() {
  printf '%s== antigravity.sh uninstall ==%s  %s\n' "$B" "$X" "$( ((DRY_RUN)) && echo '(dry-run)')"
  header "Remove generated agy hook shims + template"
  remove_file "$START_SHIM"
  remove_file "$PRE_SHIM"
  remove_file "$WORK_SHIM"
  remove_file "$POST_SHIM"
  remove_file "$TEMPLATE"
}

cmd_status() {
  printf '%s== antigravity.sh status ==%s\n' "$B" "$X"
  header "Generated shims + template ($HOOKS_DIR)"
  for path in "$START_SHIM" "$PRE_SHIM" "$WORK_SHIM" "$POST_SHIM" "$TEMPLATE"; do
    if [[ -f "$path" ]]; then ok "$path" "present"; else warn "$path" "missing"; fi
  done
  info "global ~/.gemini hooks: none — agy only reads per-worktree .agents/hooks.json (refuted live)"
}

case "$OP" in
  install)   cmd_install ;;
  uninstall) cmd_uninstall ;;
  status)    cmd_status ;;
esac
